/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javafinalproject;

import java.util.Scanner;

/**
 *
 * @author Asus
 */
public class Series extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Series.class.getName());

    /**
     * Creates new form Series
     */
    public Series() {
        initComponents();
        
        TextArea1.setEditable(false);  // para dili mabutngan og text ang text area for result
        this.setLocationRelativeTo(null);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        Combo1 = new javax.swing.JComboBox<>();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        TextField1 = new javax.swing.JTextField();
        TextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        Label4 = new javax.swing.JLabel();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        Label1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Label1.setText("Voltage Current Resistance Calculator");

        Combo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose to solve", "Voltage", "Current", "Resistance" }));
        Combo1.addActionListener(this::Combo1ActionPerformed);

        Label2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Label3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        TextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        TextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        TextArea1.setColumns(20);
        TextArea1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TextArea1.setRows(5);
        jScrollPane1.setViewportView(TextArea1);

        Label4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label4.setText("   Result");

        Button1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Button1.setText("Calculate");
        Button1.addActionListener(this::Button1ActionPerformed);

        Button2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Button2.setText("Reset");
        Button2.addActionListener(this::Button2ActionPerformed);

        Button3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Button3.setText("Main Menu");
        Button3.addActionListener(this::Button3ActionPerformed);

        jLabel1.setText("Note: Use comma for  multiple resistance");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(Button3)
                .addContainerGap())
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addGap(100, 100, 100))))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label1)
                .addGap(18, 18, 18)
                .addComponent(Combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        
        // clear the input in the textfield box
        TextField1.setText("");
        TextField2.setText("");
        TextArea1.setText("");
        Combo1.setSelectedIndex(0); // reset dropdown to top
        // resetsn the label to default
        Label2.setText(""); 
        Label3.setText("");

    }//GEN-LAST:event_Button2ActionPerformed

    private void Combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo1ActionPerformed
       
        String chosen = Combo1.getSelectedItem().toString().trim();

        if (chosen.equals("Voltage")) {    // from the jcombo, if voltage is selected the designated label will have its text based on the condition under this line of code, and others  follows depends on the chosen items
            Label2.setText("Current (I):");
            Label3.setText("Resistance (R):");
        } else if (chosen.equals("Current")) {
            Label2.setText("Voltage (V):");
            Label3.setText("Resistance (R):");
        } else if (chosen.equals("Resistance")) {
            Label2.setText("Voltage (V):");
            Label3.setText("Current (I):");
        }
    }//GEN-LAST:event_Combo1ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed

        Physics MainMenu = new Physics();
        MainMenu.setVisible(true);   // to make the "Physics" jframe appears
        this.dispose();    // to close the current "Series" jframe para dili mag pile ang mga frames and to make only one appears

    }//GEN-LAST:event_Button3ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed

        try {
            //  get the mode voltage, current, or resistance
            String mode = Combo1.getSelectedItem().toString().trim();

            if (TextField1.getText().isEmpty()) {
                TextArea1.setText("Error: Input 1 is empty.");
                return;
            } 
            Scanner input = new Scanner(TextField1.getText());
            double val1 = input.nextDouble();

            // to process the second box (Series components)
            String inputString = TextField2.getText();
            if (inputString.isEmpty()) {
                TextArea1.setText("Error: Input 2 is empty.");
                return;
            }

            String[] rawNumbers = inputString.split(",");
            double[] valuesArray = new double[rawNumbers.length]; // Create the array

            // Loop to fill the array
            for (int i = 0; i < rawNumbers.length; i++) {
                valuesArray[i] = Double.parseDouble(rawNumbers[i].trim());
            }

            // loop to sum the array 
            double val2 = 0;
            for (double v : valuesArray) {
                val2 += v;
            }

            double numericResult = 0.0;

            switch (mode) {
                case "Voltage":
                    // V = I * R
                    numericResult = val1 * val2;
                    break;

                case "Current":
                    // I = V / R
                    if (val2 != 0) {
                        numericResult = val1 / val2;
                    }
                    break;

                case "Resistance":
                    // R = V / I
                    if (val2 != 0) {
                        numericResult = val1 / val2;
                    }
                    break;
            }

            String unit = "";
            switch (mode) {
                case "Voltage":
                    unit = " V"; // Volts
                    break;
                case "Current":
                    unit = " A";  // Ampere
                    break;
                case "Resistance":
                    unit = "Ohms";  
                    break;
            }

            // displaying the final result
            TextArea1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));  // to adjust the text size bigger, because changing it at the jframe could  also change the size of the text area
            TextArea1.setText("Result: " + String.format("%.2f", numericResult) + unit); // %.2f kay ilimit ang decimal into two places

        } catch (Exception e) {
            TextArea1.setText("Error: Check your numbers.\nUse commas for the list (e.g. 10, 20).");
        }

    }//GEN-LAST:event_Button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Series().setVisible(true));  // if this  will be the code input in the methods in javafinalproject file then the first jframe will be disregarded
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JComboBox<String> Combo1;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JPanel Panel1;
    private javax.swing.JTextArea TextArea1;
    private javax.swing.JTextField TextField1;
    private javax.swing.JTextField TextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
